version: 2
jobs:
  test_android:
    docker:
      - image: circleci/node:8.14.0

    working_directory: ~/openchs-client

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-{{ checksum "packages/openchs-android/package.json" }}
          - v1-dependencies-

      - run: sudo apt-get install make

      - run: make deps_ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - save_cache:
          paths:
           - packages/openchs-android/node_modules
          key: v1-dependencies-{{ checksum "packages/openchs-android/package.json" }}

      - run: make ci test-android



  test_health_modules:
    docker:
      - image: circleci/node:8.14.0

    working_directory: ~/openchs-client

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-{{ checksum "packages/openchs-health-modules/package.json" }}
          - v1-dependencies-

      - run: sudo apt-get install make

      - run: make deps_ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - save_cache:
          paths:
           - packages/openchs-health-modules/node_modules
          key: v1-dependencies-{{ checksum "packages/openchs-health-modules/package.json" }}

      - run: make ci test-health-modules


  test_models:
    docker:
      - image: circleci/node:8.14.0

    working_directory: ~/openchs-client

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-{{ checksum "packages/openchs-models/package.json" }}
          - v1-dependencies-

      - run: sudo apt-get install make

      - run: make deps_ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - save_cache:
          paths:
           - packages/openchs-models/node_modules
          key: v1-dependencies-{{ checksum "packages/openchs-models/package.json" }}

      - run: make ci test-models

  release_android_staging:
    docker:
      - image: openchs/react-native-image:latest
        environment:
          - TERM: dumb
          - ENVFILE: .env.staging
          - GRADLE_OPTS: "-Xmx512m -Xms512m -Dorg.gradle.daemon=false"


    working_directory: ~/openchs-client

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "packages/openchs-android/android/app/build.gradle" }}
          - v1-dependencies-

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "packages/openchs-android/package-lock.json" }}

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "packages/openchs-health-modules/package-lock.json" }}

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "packages/openchs-models/package-lock.json" }}

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}

      - run: sudo chmod a+x packages/openchs-android/android/gradlew

      - run: make deps_ci;

      - save_cache:
          key: v1-dependencies-{{ checksum "packages/openchs-health-modules/package-lock.json" }}
          paths:
            - packages/openchs-health-modules/node_modules

      - save_cache:
          key: v1-dependencies-{{ checksum "packages/openchs-models/package-lock.json" }}
          paths:
            - packages/openchs-models/node_modules

      - save_cache:
          key: v1-dependencies-{{ checksum "packages/openchs-android/package-lock.json" }}
          paths:
           - packages/openchs-android/node_modules


      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
           - node_modules

      - run: make release_staging

      - save_cache:
          key: v1-dependencies-{{ checksum "packages/openchs-android/android/app/build.gradle" }}
          paths:
           - ~/.gradle
           - ~/.m2
           - ~/openchs-client/packages/openchs-android/android/app/.gradle
           - ~/openchs-client/packages/openchs-android/android/.gradle

      - store_artifacts:
          path: packages/openchs-android/android/app/build/outputs/apk/release/app-release.apk
          destination: openchs.apk

      - store_artifacts:
          path: packages/openchs-android/android/app/build/generated/sourcemap.js
          destination: sourcemap.js

  release_android_live:
      docker:
        - image: openchs/react-native-image:latest
          environment:
            - TERM: dumb
            - ENVFILE: .env.live
            - GRADLE_OPTS: "-Xmx512m -Xms512m -Dorg.gradle.daemon=false"


      working_directory: ~/openchs-client

      steps:
        - checkout

        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "packages/openchs-android/android/app/build.gradle" }}
            - v1-dependencies-

        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "packages/openchs-android/package-lock.json" }}

        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "packages/openchs-health-modules/package-lock.json" }}

        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "packages/openchs-models/package-lock.json" }}

        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}

        - run: sudo chmod a+x packages/openchs-android/android/gradlew

        - run: make deps_ci;

        - save_cache:
            key: v1-dependencies-{{ checksum "packages/openchs-health-modules/package-lock.json" }}
            paths:
              - packages/openchs-health-modules/node_modules

        - save_cache:
            key: v1-dependencies-{{ checksum "packages/openchs-models/package-lock.json" }}
            paths:
              - packages/openchs-models/node_modules

        - save_cache:
            key: v1-dependencies-{{ checksum "packages/openchs-android/package-lock.json" }}
            paths:
             - packages/openchs-android/node_modules


        - save_cache:
            key: v1-dependencies-{{ checksum "package-lock.json" }}
            paths:
             - node_modules

        - run: make release

        - save_cache:
            key: v1-dependencies-{{ checksum "packages/openchs-android/android/app/build.gradle" }}
            paths:
             - ~/.gradle
             - ~/.m2
             - ~/openchs-client/packages/openchs-android/android/app/.gradle
             - ~/openchs-client/packages/openchs-android/android/.gradle

        - store_artifacts:
            path: packages/openchs-android/android/app/build/outputs/apk/app-release.apk
            destination: openchs.apk

        - store_artifacts:
            path: packages/openchs-android/android/app/build/generated/sourcemap.js
            destination: sourcemap.js

workflows:
  version: 2
  test_all:
    jobs:
      - release_android_staging
      - test_models
      - test_android:
          requires:
            - test_models
      - test_health_modules:
          requires:
            - test_models
            - test_android
      - hold_staging:
          type: approval
          requires:
            - test_android
            - test_health_modules
            - test_models
      - hold_live:
          type: approval
          requires:
            - test_android
            - test_health_modules
            - test_models
      - release_android_live:
          requires:
            - hold_live

notify:
  webhooks:
    - url: https://webhooks.gitter.im/e/0fdffde721194986f2a0
